name: Tourism Project Pipeline

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  HF_TOKEN: ${{ secrets.HF_TOKEN }}

jobs:

  register-dataset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r tourism_project/requirements.txt

      - name: Upload Dataset to Hugging Face
        run: python tourism_project/data/data_register.py
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}

  data-prep:
    needs: register-dataset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r tourism_project/requirements.txt

      - name: Run Data Preparation
        run: python tourism_project/model_building/prep.py
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}

  model-training:
    needs: data-prep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r tourism_project/requirements.txt

      - name: Start MLflow server
        run: |
          nohup mlflow ui --host 0.0.0.0 --port 5000 &
          sleep 10

      - name: Train Model
        run: python tourism_project/model_building/train.py
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}

  deploy-hosting:
    needs: [register-dataset, data-prep, model-training]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r tourism_project/requirements.txt

      - name: Deploy to Hugging Face Spaces
        run: python tourism_project/hosting.py
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
